### ISSUE TITLE
[Bug]: Vehicle Gift Doesn't Work

### ISSUE THREAD

**Issue by Delisten** [Deadlineem/Extras-Addon-for-YimMenu#100] opened 2024-07-14 22:43 UTC
### Description

When pressing "gift vehicle" button, the giftee gets kicked from the vehicle.

### Steps to Reproduce

Drive out of garage, drive back in, walk out, giftee gets in vehicle, gifter presses gift button, giftee gets kicked.

### Version

- [X] I've confirmed the issue exists on the latest version

**Comment by USBMenus** [comment] 2024-07-14 22:57
im pretty sure its patched, just hasnt been removed from the script yet

**Comment by Delisten** [comment] 2024-07-14 23:04
is there any alternatives to gifting cars?

**Comment by Deadlineem** [comment] 2024-07-14 23:05
> is there any alternatives to gifting cars?

Unfortunately, no, not at this time.  Even paid menus like Stand and 2Take1 got the gifting system patched as well.

**Comment by Deadlineem** [comment] 2024-07-15 08:58
closing as duplicate of #98 it will get fixed as soon as there are some workarounds.

**Closed by Deadlineem** 2024-07-15 08:58 UTC
Labels: bug
